### ISSUE TITLE
[Question/Review/Potential-Issue] - MNIST Dataset written using tfjs-data

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/tfjs-data#101]
Hi,

Thanks for the good work here.

I wrote a simple dataset class for MNIST here (https://github.com/ksachdeva/tfjs-data-mnist). I was wondering if you could look at it and provide feedback if this is the correct approach. 

I am not happy about duplication of data that I do to pre-create the tensors. Is there a better/lazy approach to this ?

Lastly but mostly importantly when I use the Dataset with fitDataset api of Model class I get an error if I specify more than 1 Epoch for training.

This works -

```typescript
await model.fitDataset(ds.trainDataset.batch(32), {
    epochs: 1,
    callbacks: {
      onBatchEnd: async (batch: number, logs?: tf.Logs) => {
        batchProgressEl.innerText =
            `${batch} - ${logs['loss']} -  ${logs['acc']}`;
      },
      onEpochEnd: async (epoch: number, logs?: tf.Logs) => {
        epochEndResultEl.innerText =
            `${epoch} - ${logs['loss']} -  ${logs['acc']}`;
      }
    }
  });
```
and this fails at the start of Epoch 1 (Epoch 0 runs fine)

```typescript
await model.fitDataset(ds.trainDataset.batch(32), {
    epochs: 2,  // NUMBER OF EPOCHS is 2 
    callbacks: {
      onBatchEnd: async (batch: number, logs?: tf.Logs) => {
        batchProgressEl.innerText =
            `${batch} - ${logs['loss']} -  ${logs['acc']}`;
      },
      onEpochEnd: async (epoch: number, logs?: tf.Logs) => {
        epochEndResultEl.innerText =
            `${epoch} - ${logs['loss']} -  ${logs['acc']}`;
      }
    }
  });
`
The error I get is -

```typescript
tensor.ts:587 Uncaught (in promise) Error: Tensor is disposed.
    at e.throwIfDisposed (tensor.ts:587)
    at e.dataSync (tensor.ts:564)
    at shapeAndValues (dataset.ts:429)
    at batchConcat (dataset.ts:401)
    at deepBatchConcat (dataset.ts:379)
    at deepZipInternal (deep_map.ts:144)
    at _loop_1 (deep_map.ts:159)
    at deepZipInternal (deep_map.ts:157)
    at Object.deepZip (deep_map.ts:128)
    at MapIterator.transform (lazy_iterator.ts:369)
```

There is an example in the repository as well and README has detailed instruction on how to run it. 

The example code is at https://github.com/ksachdeva/tfjs-data-mnist/blob/master/examples/src/train.ts  (In the code the value of Epoch is 1 and if you want to reproduce the error change it to 2)

Most likely it is because of my lack of understanding of tensor memory management but not able to see the reason.

Would appreciate if you could provide some feedback and guidance.

Regards & thank
Kapil

**Comment by kangyizhang** [comment]
Hi @ksachdeva 

Thank you for using tfjs and really appreciate your feedback. 

(1) currently this library does not support image, so there has to be some pre-processing of converting image into array of float/number, I'll add a readme document to list upcoming features. But you do not need to create your own dataset class inherit from `Dataset` and worry about implementing `iterator`. You can you `tf.data.array()` to generate a dataset from array of `DataElement`. 

(2) @caisq @davidsoergel please correct me if I'm wrong, `model.fitDataset` will dispose `xsAndYs` (https://github.com/tensorflow/tfjs-layers/blob/master/src/engine/training_dataset.ts#L376) for better memory management, so in your case the original data lost after epoch one. If using array of float/number at https://github.com/ksachdeva/tfjs-data-mnist/blob/master/src/data.ts#L29 there should be such concern.

**Comment by kangyizhang** [comment]
hi @ksachdeva 

I pushed a PR which works on my local machine. It is obviously not the best approach, but hopefully you can get an idea from it about using tfjs-data.

**Comment by ksachdeva** [comment]
Many thanks @kangyizhang for taking the time to sort out the issue and suggest best practices.

I have done few follows .. main change is really removal of ImageDataset class (as you suggested in your previous comment i..e simply use tf.data.array() to generate a dataset from array of DataElement)
